version: '3.2'

services:
  openkm:
    image: openkm/openkm-ce:6.3.9
    ports:
      - 8080:8080   
    volumes:
      - ./server.xml:/opt/tomcat/conf/server.xml
      - ./OpenKM.cfg:/opt/tomcat/OpenKM.cfg
      - ./repository:/opt/tomcat/repository
    links:
      - mysql:mysql

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      - MYSQL_DATABASE=okmdb
      - MYSQL_USER=openkm
      - MYSQL_PASSWORD=openkm
      - MYSQL_ROOT_PASSWORD=openkm
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql:/var/lib/mysql
      